### ISSUE TITLE
couldn't use strings in rednotes code, why?

### ISSUE THREAD

**Issue by thaislescano** [thaislescano/rednotas#2]
(só um teste)

**Comment by danilocaverna** [comment]
acho que a gente deve ter feito algo errado antes. agora deu tudo certo (y)

**Comment by danilocaverna** [comment]
da pra fechar essas aqui?

**Comment by thaislescano** [comment]
você achou o labels ali na direita?

**Comment by thaislescano** [comment]
a gente pode lock

**Comment by danilocaverna** [comment]
não achei ;/

Date: Thu, 17 Mar 2016 04:48:04 -0700

**Comment by danilocaverna** [comment]
eu não achei ;/

Date: Thu, 17 Mar 2016 04:48:49 -0700

**Comment by danilocaverna** [comment]
acho que só vc pode fazer um branch novo ai

Date: Thu, 17 Mar 2016 04:48:49 -0700

**Comment by danilocaverna** [comment]
http://191.249.116.129:8090/redmaths/

Date: Thu, 17 Mar 2016 04:48:49 -0700
