### ISSUE TITLE
Criar versão online do redmaths.

### ISSUE THREAD

**Issue by danilocaverna** [thaislescano/rednotas#5]
Criar um novo branch pra acomodar a versão online do redmaths.

**Comment by danilocaverna** [comment]
Não sei como faz pra adicionar Label.

**Comment by thaislescano** [comment]
Oi, cheguei :} vai em pull requests

**Comment by danilocaverna** [comment]
https://github.com/JustArchi/ArchiSteamFarm/issues

Date: Thu, 17 Mar 2016 04:45:38 -0700
